/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_cognito_identity_pool_id": "eu-west-3:30e46809-610c-45a8-805c-fb4a3e28825b",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_HuBLpnFU5",
    "aws_user_pools_web_client_id": "2qgv2a44tq6snkr07n6citi0bl",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://t4qkwlkemrcu3epxu3v4kwwtqe.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-g5v4ww3475hytmftnodkovfcsu",
    "awsExports": {
        "REGION": "eu-west-3",
        "USER_POOL_ID": "eu-west-3_EvG6oTdC7",
        "USER_POOL_APP_CLIENT_ID": "5ppfpr6i7299gnoft28uokhf7e"
    }
};


export default awsmobile;
